(ns torrent-client.protocol.main)

(defprotocol Protocol
  (send-data [client data] [client type data] "")
  (send-handshake [client] "")
  (send-extended [client id message] [client id message data] "")
  (send-extended-handshake [client] "")
  (send-metadata-request [client piece-index] "")
  (send-metadata-piece [client piece-index info-length data] "")
  (send-metadata-reject [client piece-index] "")
  (send-choke [client] "")
  (send-unchoke [client] "")
  (send-interested [client] "")
  (send-not-interested [client] "")
  (send-have [client index] "")
  (send-bitfield [client] "")
  (send-request [client index begin piece] "")
  (send-block [client index begin piece] "")
  (send-cancel [client index begin piece] "")
  )